[package]
name = "sp1-benchmarks-eval"
version = "0.1.0"
edition = "2021"

[build-dependencies]
vergen = { version = "8", default-features = false, features = [
  "build",
  "git",
  "git2",
] }

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
csv = "1.3.0"
serde = { version = "1.0.207", features = ["derive"] }
bincode = "1.3.3"
serde_json = "1.0"
chrono = "0.4.38"

# sp1
sp1-prover = { git = "https://github.com/succinctlabs/sp1", rev = "55b10a22cd5d0e52bf12ce6d096a4eb74eb459f0" }
sp1-core-executor = { git = "https://github.com/succinctlabs/sp1.git", rev = "55b10a22cd5d0e52bf12ce6d096a4eb74eb459f0" }
sp1-core-machine = { git = "https://github.com/succinctlabs/sp1.git", rev = "55b10a22cd5d0e52bf12ce6d096a4eb74eb459f0" }
sp1-cuda = { git = "https://github.com/succinctlabs/sp1.git", rev = "55b10a22cd5d0e52bf12ce6d096a4eb74eb459f0", optional = true }
sp1-stark = { git = "https://github.com/succinctlabs/sp1.git", rev = "55b10a22cd5d0e52bf12ce6d096a4eb74eb459f0" }

# risc0
risc0-zkvm = { version = "=1.1.3", default-features = false, features = [
  "prove",
], optional = true }

# sp1-reth
sp1-reth-primitives = { git = "https://github.com/succinctlabs/sp1-reth.git", branch = "john/update-for-v1" }

[features]
default = []
cuda = ["dep:sp1-cuda", "risc0-zkvm?/cuda"]
risc0 = ["dep:risc0-zkvm"]
